[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
default_to_workspace = false

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.clippy]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--all", "--", "-D", "warnings"]

[tasks.test]
command = "cargo"
args = ["test", "--tests"]

[tasks.udeps]
install_crate = "cargo-udeps"
command = "cargo"
args = ["udeps"]

[tasks.validate]
run_task = { name = ["format", "clippy", "test", "udeps"] }

[tasks.star_demo]
command = "cargo"
args = ["run", "--bin", "star_demo"]


[tasks.keyboard_integration_test]
command = "cargo"
env = { "BITT_SCRIPT" = "keyboard" }
args = ["run", "--bin", "star_test"]

[tasks.controller_integration_test]
command = "cargo"
env = { "BITT_SCRIPT" = "controller" }
args = ["run", "--bin", "star_test"]

# Bevy stores mouse position in window, this won't work in headless mode
[tasks.mouse_integration_test]
command = "cargo"
args = ["run", "--bin", "click_demo", "--", "three-clicks"]

[tasks.integration_test]
run_task = { name = [
    "controller_integration_test",
    "keyboard_integration_test",
    "mouse_integration_test",
] }

[tasks.headless_integration_test]
run_task = { name = [
    "controller_integration_test",
    "keyboard_integration_test",
] }
env = { "HEADLESS" = "true" }

[tasks.ci_integration_test]
run_task = "integration_test"
env = { "CI" = "true" }

[tasks.headless_ci_integration_test]
run_task = "headless_integration_test"
env = { "CI" = "true" }
