[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
default_to_workspace = false

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.clippy]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--all", "--", "-D", "warnings"]

[tasks.test]
command = "cargo"
args = ["test", "--tests"]

[tasks.udeps]
install_crate = "cargo-udeps"
command = "cargo"
args = ["udeps"]

[tasks.validate]
run_task = { name = ["format", "clippy", "test", "udeps"] }

[tasks.demo_game]
command = "cargo"
args = ["run", "--bin", "main"]


[tasks.keyboard_integration_test]
command = "cargo"
args = ["run", "--bin", "keyboard_integration_test"]


[tasks.controller_integration_test]
command = "cargo"
args = ["run", "--bin", "controller_integration_test"]

[tasks.integration_test]
run_task = { name = [
    "keyboard_integration_test",
    "controller_integration_test",
] }

[tasks.ci_integration_test]
run_task = "integration_test"
env = { "CI" = "true" }
