[package]
name = "bitt"
description = "Bevy integration testing toolkit"
repository = "https://github.com/haihala/Bevy-integration-testing-toolkit"
version = "0.1.0"
edition = "2021"
license-file = "../../LICENSE"
readme = "../../README.md"

keywords = ["bevy", "testing"]

[dependencies]
bevy = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
