[package]
name = "click_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
clap = { workspace = true }

bitt = { path = "../bitt" }

[features]
integration_test = []
