[package]
name = "star_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy-inspector-egui = { workspace = true }
leafwing-input-manager = { workspace = true }
bevy_rapier2d = { workspace = true }

bitt = { path = "../bitt" }

[features]
integration_test = []
